services:
  backend:
    build: ./backend
    container_name: corvina_backend
    ports:
      - "5001:5001"
    volumes:
      - ./dataset:/app/dataset
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: corvina_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
